# Server Configuration
server.port=8080

# Spring Data MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/onlinebookstore
# Or default host and port:
# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=onlinebookstore

# Logging level
logging.level.com.bookstore=DEBUG
logging.level.org.springframework.data.mongodb=INFO
